plugins:
  - jekyll-feed
title: Lum's blog
author: Lum Ramabaja
# Site setings
name: 'Lum Ramabaja'
description: 'Researcher'
#meta_description: 'Jekyll template, minimal style, perfect for bloggers.'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'authorimage.jpg'
  greetings: "A blog about the stuff that interests me. Includes topics from decentralised systems, algorithms, biology, and more."
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://royce.netlify.com/
disqus: 'Lum'
#mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: 

use_math: true
# Contact form setings
email: lumramabaja@gmail.com
contact_page_description: "Ask me anything!"
thankyou_page_description: "Your message has been successfully sent!"

# Social links
twitter: 'LumRamabaja'
#facebook: 'username'
github: 'LumRamabaja'
metoken: '0xd9c796cA89EeDCc26165026FaDBDc3deD42009a8'
rss: 'https://irwt/feed.xml '
#codepen: 'username'
#dribbble: 'username'
#medium: '@username'
#instagram: 'username'
#pinterest: 'username'
#linkedin: 'username'
#producthunt: '@username'
#quora: 'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  #- text: Style Guide
  #  url: /style-guide
  - text: Contact Me
    url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
